[tool.poetry]
name = "pyshop"
version = "0.1.0"
description = ""
authors = ["Brian Bell <bellbm@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "2.1.15"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
